### PR TITLE
Add python dependencies

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
I wonder what we should concerning gdal.
I think it would be good to have gdal2 always installed with `--with-python3`, the question is if this dependency should be done in the main `gdal2` formula in the osgeo tap, or in this formula.

**Comment by dakcarto** [comment]
> I wonder what we should concerning gdal.
> I think it would be good to have gdal2 always installed with --with-python3, the question is if this dependency should be done in the main gdal2 formula in the osgeo tap, or in this formula.

I've added the missing required option in ec029ad. Thanks!

Currently, Python 3 is still considered non-default in Homebrew (at least to my knowledge). So, the `gdal2` formula should not automatically install the Python 3 Homebrew package by default.

**Comment by m-kuhn** [comment]
ec029ad looks like the correct solution in this case.

What's your opinion about the other (`pip3`) dependencies in this pr?
QGIS functionality is much reduced without these packages installed.

There are also packages like `mock`, `nose2` etc. but they are more for building (or better, testing), so they shouldn't be required by default I think.

**Comment by dakcarto** [comment]
> What's your opinion about the other (pip3) dependencies in this pr?
> QGIS functionality is much reduced without these packages installed.

They look fine (I'm putting together a commit now that will supersede this PR). The one for `numpy` is not needed since this is [already a requirement](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/gdal2.rb#L94) of dependent `gdal2 --with-python3`.

> There are also packages like mock, nose2 etc. but they are more for building (or better, testing), so they shouldn't be required by default I think.

I've added those to the Caveats section as recommend packages for development. Agreed, they should not be a requirement.

_What about `matplotlib` and `pyparsing`? Are those still considered a Python dependency?_


**Note about Python dependencies**

The general rule at Homebrew is that formulae should not install Python third-party packages, unless the formula itself is a Python package, e.g. `pyqt5`. The accepted practice is to 'vendor' these dependencies into `<formula prefix>/libexec/vendor/lib/pythonX.X/site-packages`, kind of a formula `vitualenv`. Often, this means downloading Python package source and running `setup.py`, etc. and installing to `libexec`. Although, I have found a nice way to do this using `pip` if it is available (was not in a standard macOS Python 2.7). Vendoring also allows for specific versions of packages to be used, much like `virtualenv`.

Vendoring the package dependencies is handy (nicer for automated builds than multiple blocking `depends_on`), but you need to ensure the QGIS launch wrappers (Info.plist, shell launch script) have the additional PYTHONPATH for `libexec/vendor/lib/pythonX.X/site-packages` and that users building standalone PyQGIS apps know where to find them, i.e. need listed in the Caveats. In this regards, and the fact that this is a 'dev' formula, I think hard dependencies, instead of vendoring, might be OK, since the user really _should_ want those in their Python `site_packages`.

Opinions? I don't see major issues with vendoring the simpler needed modules.

**Comment by m-kuhn** [comment]
We could treat the pyqgis package which is part of the qgis formula as a Python package, just like pyqt5 I think. After all, they are both sip packages offering access to Qt or QGIS...

The option of vendoring sounds nice as well.

I'd include `matplotlib` I think. I don't know where `pyparsing` is needed.

**Comment by m-kuhn** [comment]
I think that has all been sorted out already with 9b9e005c2bf0a22007e7

**Pull request closed without merging**
