### PR TITLE
Add troubleshoot for failure in running scripts/sip_include.sh.

### PR DESCRIPTION
**Pull request by ismailsunni**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Could the vash version check be included directly in the bash script? I think that would be much more targetted than here.

**Comment by ismailsunni** [comment]
That's better idea, @m-kuhn.
I have made a PR here : https://github.com/qgis/QGIS/pull/4927

**Comment by m-kuhn** [comment]
Thanks for the quick reaction, looks good

**Comment by ismailsunni** [comment]
Thanks for your suggestion. I will close this then.

**Pull request closed without merging**
